### ISSUE TITLE
Alpha release

### ISSUE THREAD

**Issue by tmpfs** [uwe-app/app#368]
Tracking the tasks for an alpha release.

## Live reload

* [x] Support collections with live reload (#357)
* [x] Support JIT cache with live reload (#359)

## Content

* [ ] Publish blog announcing alpha, other articles should be drafts until reviewed
* [ ] Documentation #319 #347 #147 #334 #244 #378 

## Branding

* [ ] Integrate brand logo and color schemes with the website
* [ ] Set icon for discord and twitter
* [ ] Use open graph social image
* [ ] Use favicon
* [ ] Github org avatar

## Web pages and sites

* [ ] Marketing website (`uwe.app`)
* [ ] Releases page (`releases.uwe.app`)
* [ ] Local server default index page (when no virtual hosts can be found) (`default_index.html`)
* [ ] Default 404 page for the local server, eg: `https://127.0.0.1:8843/foo.html` (`default_not_found.html`)
* [ ] Render error page, when a live reload SSR encounters a compiler error (`error.html`)

## Misc

* [x] Draft handling (#367)
* [x] Publish redirects (#40)
* [x] Lock file bug (#314)
* [x] Fix redirects bug (#369)

/cc @chrism
